version: '3.8'

services:
  dependencies:
    build:
      context: .
      dockerfile: Dockerfile
  machine_learning:
    container_name: ml_service
    build: ./machine_learning
    ports:
      - '8080:8080'
    restart: always
  app:
    container_name: scraper_app
    build: ./app
    depends_on:
      - db
    volumes:
      - .container_images:/src/images
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env
  db:
    container_name: scraper_postgres
    image: postgres
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always