version: '3.8'

services:
  app:
    container_name: scraper_app
    build: ./
    depends_on:
      - db
#    command: "bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.ScraperController:app
#    --reload'"
    volumes:
      - .container_images:/src/images
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env
  db:
    container_name: scraper_postgres
    image: postgres
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always